### ISSUE TITLE
Logo Height : 0

### ISSUE THREAD

**Issue by Fumiaki-Tanaka** [wpexplorer/wpex-mesa#1]
Hi WP Explorer, Thank you for sharing beautiful theme.

I just found that I can not add logo on header.
since the header image set as height 0, I guess.
So that when I upload image and try to crop image.
I am even not able to crop. all of image is covered by gray like below.

Hope your support.
Fumi

<img width="327" alt="2017-10-18 12 54 29" src="https://user-images.githubusercontent.com/27329861/31702809-9c3e138a-b403-11e7-89ca-e199a5c6d67d.png">

<img width="1145" alt="2017-10-18 12 55 00" src="https://user-images.githubusercontent.com/27329861/31702810-9c75ca46-b403-11e7-8fa8-f0bda6e886e8.png">

**Comment by wpexplorer** [comment]
This theme doesn't use the WordPress 'header image' function. To add your logo go to Appearance > Customize > General Theme Settings > Header: https://cl.ly/nA3Y

**Comment by Fumiaki-Tanaka** [comment]
Thank you for response, It helps me!
